server:
  port: 18080
  # tomcat支持中文 解决Swagger2 文档bug
  tomcat:
    uri-encoding: UTF-8
spring:
  name: restaurante
  #数据校验的国际化
  messages:
    encoding: UTF-8
    basename: i18n/validation
  jackson: # 时间 json
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC # europe/madrid
  datasource:
    url: jdbc:mysql://www.yqfsoft.com:3306/yqfsoftrestaurante?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: qingfengmysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        #login-username: admin
        #login-password: 123456
        #禁止那些ip
        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  # 对上传文件的定义
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0  # 支持文件写入磁盘
      max-file-size: 2MB      # 单个文件上传最大值
      max-request-size: 20MB  # 最大批量上传文件大小峰值
  # redis 配置
  redis:
    host: www.yqfsoft.com
    port: 6379
    password: qingfengredis
    database: 0
    timeout: 10000 # 客户端超时时间单位是毫秒 默认是2000
    lettuce:
      pool:
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 500 # 连接池中的最大空闲连接 默认 8
        min-idle: 50 # 连接池中的最小空闲连接 默认 0
        max-active: 2000 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        shutdown-timeout: 100 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # 缓存使用redis
  cache:
    type: redis
  # 支持中文 主要是Swagger2文档接口
  http:
    encoding:
      charset: UTF-8
      #force: true
      enabled: true
  # 开发环境
  #profiles:
    #active: dev
debug: true
# mybatis-plus mapper xml文件存放的地方
mybatis-plus:
  mapper-locations: classpath*:com/yqfsoft/servicecenter/**/mapper/xml/*Mapper.xml
  configuration:
    #查看sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志系统
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: error